import Head from 'next/head'
import Inventory from '../components/inventory/Inventory'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container" data-bs-theme="dark">
        <div className="row">
          <div className="col">
            <h1>PDC Inventory</h1>
          </div>
        </div>
        <div className="row">
          <div className="col">
            <Inventory />
          </div>
        </div>
      </main>
    </>
  )
}
